# Generated by Django 4.2.7 on 2023-12-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_ucs_user_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=50, unique=True),
        ),
    ]
