# Generated by Django 4.2.7 on 2023-11-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("discussions", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
        migrations.AddField(
            model_name="discussion",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
        migrations.AddField(
            model_name="discussion",
            name="replies",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="discussions.reply"
            ),
        ),
        migrations.AddField(
            model_name="discussion",
            name="tags",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="discussions.tag"
            ),
        ),
    ]
