# Generated by Django 4.2.7 on 2023-12-10 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discussions", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reply",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="Discussion",
        ),
        migrations.DeleteModel(
            name="Reply",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
